#!/usr/bin/env sh
# Takes a batch of frame sequences and renders them to individual lossless video file. Will use ./input and ./output folders from current working path.

bold=$(tput bold)
normal=$(tput sgr0)

if [ ! -d "input" ]; then
    echo "! ${bold}./input directory does not exist.${normal}"
    exit 1
fi

mkdir -p output

for d in input/*; do
    INPUT=${d#input/}

    if [ -f "output/${INPUT}.mov" ]; then
        echo "~~~${bold}Skipping ${INPUT}, output/${INPUT}.mov already exists...${normal}"
        continue
    fi

    commando runger-sort "input/${INPUT}"

    # don't call runger-render if runger-sort failed
    if [ $? -eq 0 ]; then
        commando runger-render $INPUT
    fi
done
