#!/usr/bin/env sh
# Takes a directory of frame sequences and renders to a lossless video.
# @param <ID> - Shot ID. Must exist within ./input subdirectory and be presorted.
# @param <FPS> - FPS to use for render. Defaults to 30.
# @param <qscale> - Quality scale. Defaults to 13. 0 is best, 32 which is worst. Sweetspot is 9 - 13
# @param <size> - Frame size. Defaults to 1920x1080.

ID=${1%/}
FPS=${2:-30}
QSCALE=${3:-13}
SIZE=${4:-1920x1080}

bold=$(tput bold)
normal=$(tput sgr0)

if [ -z "${ID}" ]; then
    echo "! ${bold}Shot ID is required.${normal}"
    exit 1
fi

if [ ! -d "input" ]; then
    echo "! ${bold}./input directory does not exist.${normal}"
    exit 1
fi

if [ ! -d "input/${ID}" ]; then
    echo "! ${bold}input/${ID} directory does not exist.${normal}"
    exit 1
fi

if [ ! -f "input/${ID}/${ID}_00000.png" ]; then
    echo "! ${bold}${ID}/${ID}_00000.png file does not exist. Is the directory presorted?${normal}"
    exit 1
fi

COUNT=$(($(ls -1 input/${ID} | wc -l)))

echo "\t${bold}Rendering ${ID} (${COUNT} frames)...${normal}"

ffmpeg -loglevel panic -stats -y -probesize 5000000 -f image2 -r ${FPS} -i input/${ID}/${ID}_%05d.png -c:v prores_ks -profile:v 3 -qscale:v ${QSCALE} -vendor ap10 -pix_fmt yuv422p10le -s ${SIZE} -r ${FPS} -force_fps output/${ID}.mov
